on:
  push:
    branches:
      - main
      - reference/*
      - lectures/*
      - exercise_*

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: install dependencies
        run: npm ci
      - run: npm test

      - name: Collect Coverage from Client
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: client