on:
  push:
    branches:
      - main
      - master
      - lectures/*
      - reference/*
      - exercise_*
      - mock_exam

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: install dependencies
        run: npm ci
      - run: npm test
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
      - name: Collect coverage from client
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: client
      - name: Collect coverage from server
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: server
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo_token: hok7XKigNIJgiPAOdSuM2WOZk89bYEw0B
